# Generated by Django 4.2.11 on 2026-03-11 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('called_tricks', models.PositiveSmallIntegerField()),
                ('won_tricks', models.PositiveSmallIntegerField()),
                ('score_delta', models.IntegerField()),
                ('is_caller', models.BooleanField(default=False)),
                ('is_with', models.BooleanField(default=False)),
                ('is_dash_call', models.BooleanField(default=False)),
                ('risk', models.PositiveSmallIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='rooms.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='game.round')),
            ],
            options={
                'db_table': 'scores',
                'unique_together': {('player', 'round')},
            },
        ),
    ]
