# Generated by Django 4.2.11 on 2026-03-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tricks_called', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('trump', models.CharField(choices=[('SANS', 'Sans'), ('SPADES', 'Spades'), ('HEARTS', 'Hearts'), ('DIAMONDS', 'Diamonds'), ('CLUBS', 'Clubs'), ('PASS', 'Pass')], max_length=10)),
                ('is_pass', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bids',
            },
        ),
        migrations.CreateModel(
            name='Estimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tricks_estimated', models.PositiveSmallIntegerField()),
                ('is_dash_call', models.BooleanField(default=False)),
                ('is_with', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'estimations',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_round', models.PositiveSmallIntegerField(default=1)),
                ('is_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'games',
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField()),
                ('trump_suit', models.CharField(blank=True, choices=[('SANS', 'Sans'), ('SPADES', 'Spades'), ('HEARTS', 'Hearts'), ('DIAMONDS', 'Diamonds'), ('CLUBS', 'Clubs')], max_length=10, null=True)),
                ('round_type', models.CharField(blank=True, choices=[('OVER', 'Over'), ('UNDER', 'Under')], max_length=10, null=True)),
                ('double_score', models.BooleanField(default=False)),
                ('phase', models.CharField(choices=[('WAITING_FOR_PLAYERS', 'Waiting for Players'), ('DISTRIBUTION', 'Distribution'), ('DASH_CALL', 'Dash Call'), ('BIDDING', 'Bidding'), ('ESTIMATION', 'Estimation'), ('PLAYING', 'Playing'), ('SCORING', 'Scoring'), ('ROUND_END', 'Round End')], default='DISTRIBUTION', max_length=30)),
                ('skipped', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'rounds',
            },
        ),
        migrations.CreateModel(
            name='TrickResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tricks_won', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'trick_results',
            },
        ),
    ]
