# Generated by Django 4.2.11 on 2026-03-11 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trickresult',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trick_results', to='rooms.player'),
        ),
        migrations.AddField(
            model_name='trickresult',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trick_results', to='game.round'),
        ),
        migrations.AddField(
            model_name='round',
            name='caller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='called_rounds', to='rooms.player'),
        ),
        migrations.AddField(
            model_name='round',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game.game'),
        ),
        migrations.AddField(
            model_name='game',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='estimation',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimations', to='rooms.player'),
        ),
        migrations.AddField(
            model_name='estimation',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimations', to='game.round'),
        ),
        migrations.AddField(
            model_name='bid',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='rooms.player'),
        ),
        migrations.AddField(
            model_name='bid',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='game.round'),
        ),
        migrations.AlterUniqueTogether(
            name='trickresult',
            unique_together={('round', 'player')},
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together={('game', 'round_number')},
        ),
        migrations.AlterUniqueTogether(
            name='estimation',
            unique_together={('round', 'player')},
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('round', 'player')},
        ),
    ]
