# Generated by Django 4.2.11 on 2026-03-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='trump',
            field=models.CharField(blank=True, choices=[('SANS', 'Sans'), ('SPADES', 'Spades'), ('HEARTS', 'Hearts'), ('DIAMONDS', 'Diamonds'), ('CLUBS', 'Clubs'), ('PASS', 'Pass')], max_length=10, null=True),
        ),
    ]
